import{i as a,a as L,S}from"./assets/vendor-5401a4b0.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))n(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const c of o.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&n(c)}).observe(document,{childList:!0,subtree:!0});function s(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(t){if(t.ep)return;t.ep=!0;const o=s(t);fetch(t.href,o)}})();const h=document.querySelector(".form"),d=document.querySelector(".gallery"),q=document.querySelector("div"),v=document.querySelector("input"),p=document.querySelector(".btn-load"),y=()=>{const e=document.createElement("span");e.classList.add("loader"),q.append(e)},i=()=>{const e=document.querySelector(".loader");e&&e.remove()},E=()=>{p.style.display="block"},l=()=>{p.style.display="none"};let u=1,f=15,m=" ",g;h.addEventListener("submit",async e=>{u=1,y(),d.innerHTML=" ",e.preventDefault();try{m=v.value;const r=await b();w(r),h.reset(),i(),E(),r.hits.length<15&&l(),r.hits.length===0&&(l(),a.error({message:"Sorry, there are no images matching <br>your search query. Please try again!</br>",position:"center",transitionIn:"fadeInLeft"}))}catch{a.error({title:"Error"})}});p.addEventListener("click",async()=>{y();try{u+=1;const e=await b();w(e),i();const{height:r}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"}),(d.children.length>=g||e.hits.length<f)&&(a.warning({message:"We are sorry, but you have reached the end of search results.",position:"bottomCenter",transitionIn:"fadeInDown"}),l())}catch{a.error({title:"Error"}),i()}if(!m){showError("empty field");return}});async function b(){try{const e="42318404-1173ca802dc215ae825a9e5c8",r=new URLSearchParams({key:e,q:m,image_type:"photo",orientation:"horizontal",safesearch:!0,page:u,per_page:f}),s=await L.get(`https://pixabay.com/api/?${r}`);return g=s.data.totalHits,s.data}catch(e){throw console.log(e),WebTransportError}}function w(e){const r=e.hits.map(n=>`
            <li class="gallery-item"><a href="${n.largeImageURL}">
          <img class="gallery-image" src="${n.webformatURL}" alt="${n.tags}"></a>
          <p><b>Likes: </b>${n.likes}</p>
          <p><b>Views: </b>${n.views}</p>
          <p><b>Comments: </b>${n.comments}</p>
          <p><b>Downloads: </b>${n.downloads}</p>
          </li>`).join("");d.insertAdjacentHTML("beforeend",r),new S(".gallery a",{captions:!0,captionType:"attr",captionsData:"alt",captionPosition:"bottom",fadeSpeed:150,captionSelector:"img",captionDelay:250}).on("show.simplelightbox").refresh(),i()}
//# sourceMappingURL=commonHelpers.js.map
